### PR TITLE
Add missing dependency: `plasma-framework-dev`

### LINKED ISSUE #22: Missing dependency plasma-framework-dev
I tried to build it (in Ubuntu) but the development package for the plasma framework (plasma-framework-dev) was missing, so I get the following error from CMake:
```
CMake Error at CMakeLists.txt:11 (find_package):
  By not providing "FindKF5Plasma.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "KF5Plasma", but CMake did not find one.

  Could not find a package configuration file provided by "KF5Plasma" with
  any of the following names:

    KF5PlasmaConfig.cmake
    kf5plasma-config.cmake

  Add the installation prefix of "KF5Plasma" to CMAKE_PREFIX_PATH or set
  "KF5Plasma_DIR" to a directory containing one of the above files.  If
  "KF5Plasma" provides a separate development package or SDK, be sure it has
  been installed.
```

I solved it installing the required package:
`sudo apt install plasma-framework-dev`

Maybe it should be added to the dependencies.

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/duvholt/i3-pager/issues/22

### CODE REVIEW

**Comment by pietryszak** [comment]
This packet is not available in kubuntu 22.10
And in Debian bookworm(Debian 12) not available
In Debian 12 a package that help was is `qtdeclarative5-dev`

**Comment by SimonBrandner** [comment]
> This packet is not available in kubuntu 22.10 And in Debian bookworm(Debian 12) not available In Debian 12 a package that help was is `qtdeclarative5-dev`

That sounds like a different issue?

**Comment by pietryszak** [comment]
> > This packet is not available in kubuntu 22.10 And in Debian bookworm(Debian 12) not available In Debian 12 a package that help was is `qtdeclarative5-dev`
> 
> That sounds like a different issue?

Nope. Same issue, with same error. You just provide non existing package to solve it.

**Comment by duvholt** [comment]
To me it looks like `plasma-framework-dev` is the old package name of `libkf5plasma-dev`. 
https://packages.debian.org/sid/plasma-framework-dev

`qtdeclarative5-dev` is likely also needed. Looks like I added it to the Github actions workflow: https://github.com/duvholt/i3-pager/blob/master/.github/workflows/build.yml
I don't use Ubuntu/Debian so I have no easy way to test this other than in CI.

**Comment by SimonBrandner** [comment]
I've updated the PR by adding the deps from the GH workflow (`libkf5plasma-dev qtbase5-dev qtdeclarative5-dev`) - does that look alright?

**Comment by duvholt** [comment]
Thanks!

**Comment by SimonBrandner** [comment]
> Thanks!

No problem!

**Pull request merged**
